# Generated by Django 5.1.2 on 2024-10-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
