# Generated by Django 5.1.2 on 2024-10-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_date_end_alter_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
