# Generated by Django 5.1.2 on 2024-10-30 11:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(auto_now=True)),
                ('clock_out', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.datetime(2024, 10, 30, 11, 8, 52, 602366, tzinfo=datetime.timezone.utc))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
            },
        ),
    ]
