# Generated by Django 5.1.2 on 2024-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_clock_in_alter_attendance_clock_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
